version: '3.8'

services:
  db:
    container_name: "flask_db"
    image: mysql:8.3.0
    ports:
      - '3307:3306'
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DOCKER_DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - flask_database_vol:/var/lib/mysql
    command: [ 'mysqld' ]
    networks:
      - microservices

  flask_server:
    container_name: "flask_backend"
    build: .
    expose:
      - '5000'
    env_file:
      - .env
    environment:
      - RABBITMQ_HOST=${DOCKER_RABBITMQ_HOST}
      - DB_NAME=${DOCKER_DB_NAME}
      - DB_HOST=${DOCKER_DB_HOST}
    volumes:
      - ./app:/docker_app/app
      - ./config:/docker_app/config
      - ./consumer:/docker_app/consumer
    depends_on:
      - db
    networks:
      - microservices

volumes:
  flask_database_vol:
  rabbitmq-log:

networks:
  microservices:
    external: true
    driver: bridge