version: '2.26'

services:
  mongo_db:
    container_name: fastapi_db
    image: mongo
    restart: always
    ports:
      - '27018:27017'
    env_file:
      - .env
    volumes:
      - mongodb_vol:/data/db

  rabbitmq:
    image: rabbitmq:3.9.13
    restart: always
    container_name: rabbitmq_cont
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: full_access
      RABBITMQ_DEFAULT_PASS: s3crEt

  fastapi_server:
    container_name: "fastapi_backend"
    restart: always
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=${DOCKER_DB_HOST}
      - RABBITMQ_HOST=${DOCKER_RABBITMQ_HOST}
    volumes:
      - ./app:/product_app/app
      - ./main.py:/product_app/main.py
    depends_on:
      - mongo_db
      - rabbitmq

volumes:
  mongodb_vol:
